title: Nice to meet you, I'm Maria Séves
description: > # this means to ignore newlines until "baseurl:"
  Registering my experiences as a User Experience Master student at LCC-UAL
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Maria Carolina Séves # add your name
author-img: maria-seves.jpeg # add your photo
about-author: UX Designer who codes # add description
social-twitter: darthmaria # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: mcseves # add your Github handle
social-linkedin: mcseves # add your Linkedin handle
social-dribbble: mariaseves
social-email: mcmseves@gmail.com # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
